#!/usr/bin/python3

import sys

def factorize(value):
    i = 2
    factors = []
    
    if value < 2:
        return factors
    
    while i * i <= value:
        if value % i == 0:
            value //= i
            factors.append((i, value))
            break
        else:
            i += 1
    
    if value > 1:
        factors.append((value, 1))
    
    return factors


if len(sys.argv) != 2:
    sys.exit()

try:
    with open(sys.argv[1]) as file:
        lines = file.readlines()

        for line in lines:
            value = int(line.strip())
            results = factorize(value)

            if len(results) > 0:
                p, q = results[0]
                print("{}={}*{}".format(value, p, q))

except Exception as e:
    sys.exit()

